### ISSUE TITLE
Connection never been establish

### ISSUE THREAD

**Issue by M9Apar** [bertrandmartel/bluetooth-le-analyzer#1]
Hi, i wonder how accurate is graph value it just log values on fixed interval either it connected with device or not it just required to scan bluetooth device then it will start display graph with receive packet i wonder how would it receive data without even making connection?

**Comment by bertrandmartel** [comment]
Hello, this application just perform a LE scan to get advertising data and display the number of packet received per second. You can find more information on Bluetooth LE advertising [here](http://www.argenox.com/a-ble-advertising-primer/)
